### ISSUE TITLE
java.lang.RuntimeException: Error during updateTexImage

### ISSUE THREAD

**Issue by Kaleeswaran-Chellaiah** [webrtc/samples#1104]
USER_COMMENT=null
ANDROID_VERSION=7.1.2
APP_VERSION_NAME=1.0
BRAND=Xiaomi
PHONE_MODEL=Redmi 4A
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
at org.webrtc.SurfaceTextureHelper.updateTexImage(SurfaceTextureHelper.java:244)
at org.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:258)
at org.webrtc.SurfaceTextureHelper.access$500(SurfaceTextureHelper.java:36)
at org.webrtc.SurfaceTextureHelper$3.onFrameAvailable(SurfaceTextureHelper.java:132)
at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:207)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ErikHellman** [comment]
This is not the place to report bugs on the Android library for WebRTC. Please see https://webrtc.org/bugs for details on where to report those.

**Comment by Kaleeswaran-Chellaiah** [comment]
Hi Erikhellman,
Thanks for you information

**Comment by fukemy** [comment]
hi, now i can access to https://webrtc.org/bugs, can u help?

**Comment by hthetiot** [comment]
> hi, now i can access to https://webrtc.org/bugs, can u help?

@fukemy WebRTC bug report url is https://bugs.webrtc.org that redirect to https://bugs.chromium.org/p/webrtc/issues/list 

Cc @Kaleeswaran-Chellaiah

**Comment by fukemy** [comment]
thanks u so much
