### ISSUE TITLE
Cannot set property 'id' of undefined

### ISSUE THREAD

**Issue by initux** [webrtc/samples#1289]
some time face this issue......

TypeError: Cannot set property 'id' of undefined
at Object.update (/home/addcall_server/server/streams.js:39:17)
at Socket. (/home/addcall_server/server/socketHandler.js:13:16)
at Socket.emit (events.js:198:13)
at Socket.onevent (/home/addcall_server/node_modules/socket.io/lib/socket.js:326:8)
at Socket.onpacket (/home/addcall_server/node_modules/socket.io/lib/socket.js:286:12)
at Client.ondecoded (/home/addcall_server/node_modules/socket.io/lib/client.js:181:14)
at Decoder.Emitter.emit (/home/addcall_server/node_modules/emitter/index.js:132:20)
at Decoder.add (/home/addcall_server/node_modules/socket.io-parser/index.js:233:12)
at Client.ondata (/home/addcall_server/node_modules/socket.io/lib/client.js:166:16)
at Socket.emit (events.js:198:13)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by fippo** [comment]
there is no such file in this repository.
