### ISSUE TITLE
Python tests fail locally after the webtest change

### ISSUE THREAD

**Issue by jiayliu** [webrtc/samples#326]
Running "shell:runPythonTests" (shell) task
apprtc_test (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: apprtc_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: apprtc_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/usr/local/google/home/jiayl/code/apprtc-fork/jiayl-webrtc/samples/web/content/apprtc/apprtc_test.py", line 4, in <module>
    import webtest
  File "webtest-master/webtest/__init__.py", line 9, in <module>
    from webtest.app import TestApp
  File "webtest-master/webtest/app.py", line 32, in <module>
    from webtest.response import TestResponse
  File "webtest-master/webtest/response.py", line 5, in <module>
    from webtest import forms
  File "webtest-master/webtest/forms.py", line 7, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

**Comment by juberti** [comment]
should this move to apprtc issue tracker?
