### ISSUE TITLE
Some python tests are broken

### ISSUE THREAD

**Issue by phoglund** [webrtc/samples#717]
I updated my AppRTC checkout with npm update and ran grunt.

I got:
# 
## ERROR: apprtc_test (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: apprtc_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/usr/local/google/home/phoglund/dev/apprtc-master/out/app_engine/apprtc_test.py", line 10, in <module>
    import apprtc
  File "/usr/local/google/home/phoglund/dev/apprtc-master/out/app_engine/apprtc.py", line 17, in <module>
    import jinja2
  File "/usr/local/google/home/phoglund/dev/apprtc-master/google_appengine/lib/jinja2-2.6/jinja2/__init_.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/google/home/phoglund/dev/apprtc-master/google_appengine/lib/jinja2-2.6/jinja2/environment.py", line 18, in <module>
    from jinja2.compiler import generate
  File "/usr/local/google/home/phoglund/dev/apprtc-master/google_appengine/lib/jinja2-2.6/jinja2/compiler.py", line 13, in <module>
    from copy import deepcopy
ImportError: cannot import name deepcopy
# 
## ERROR: compute_page_test (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: compute_page_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/usr/local/google/home/phoglund/dev/apprtc-master/out/app_engine/compute_page_test.py", line 6, in <module>
    import apprtc
  File "/usr/local/google/home/phoglund/dev/apprtc-master/out/app_engine/apprtc.py", line 17, in <module>
    import jinja2
  File "/usr/local/google/home/phoglund/dev/apprtc-master/google_appengine/lib/jinja2-2.6/jinja2/__init_.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/google/home/phoglund/dev/apprtc-master/google_appengine/lib/jinja2-2.6/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
ImportError: cannot import name nodes
# 
## ERROR: analytics_page_test (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: analytics_page_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/usr/local/google/home/phoglund/dev/apprtc-master/out/app_engine/analytics_page_test.py", line 8, in <module>
    import apprtc
  File "/usr/local/google/home/phoglund/dev/apprtc-master/out/app_engine/apprtc.py", line 17, in <module>
    import jinja2
  File "/usr/local/google/home/phoglund/dev/apprtc-master/google_appengine/lib/jinja2-2.6/jinja2/__init_.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/google/home/phoglund/dev/apprtc-master/google_appengine/lib/jinja2-2.6/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
ImportError: cannot import name nodes

---

**Comment by phoglund** [comment]
Sorry, wrong repo (should have been apprtc). Never mind.
